// Pure logic for the Guardian Support Invitation - a user-controlled,
// OPTIONAL way for Nova to offer contacting a trusted person, distinct
// from Tier 1 (the always-available one-tap button in guardian-alert.ts).
// Kept free of Firestore/network I/O, same pattern as guardian-alert.ts,
// nova-tools.ts, org-risk-trend.ts.
//
// This is NOT automated crisis detection, risk scoring, or autonomous
// messaging. See docs/GUARDIAN_SUPPORT_SPEC.md §0.1, which this module is
// bound by exactly as guardian-alert.ts already is:
//
//   "Nova must not propose, design, infer, display, store, calculate, or
//   rely on any risk score, risk level, risk band, risk probability,
//   confidence score, severity score, danger rating, safety state, or
//   model-derived classification of a user's mental state."
//
// Nothing here computes, stores, or exposes anything of that shape. The
// only two things this module does are: (1) validate that a model's
// "I could offer the card" tool call is well-formed text (never risk data),
// and (2) hold the exact, pre-approved message text a user may choose to
// send - never freeform, never generated by the model. The send itself is
// dispatched exclusively through the existing, hardened
// POST /api/guardian/alert (guardian-alert.ts) - this module has no send
// capability of its own.

// Independent of GUARDIAN_ALERTS_FLAG (which gates whether a guardian
// alert can be SENT at all, and predates its own flag / defaults on
// because Tier 1 was already live before that flag existed). This flag
// gates something new - whether Nova ever OFFERS the invitation card in
// the first place - so it defaults OFF, matching
// docs/GUARDIAN_SUPPORT_SPEC.md §E.8's own migration guidance ("ship new,
// default off") rather than guardian-alert.ts's deliberate exception.
export const GUARDIAN_SUPPORT_INVITATION_FLAG = {
  id: 'guardian_support_invitation',
} as const;

export const guardianSupportInvitationEnabled = (envValue: string | undefined): boolean => envValue === 'true';

// Two pre-approved templates only - never freeform user text. See the
// header comment: docs/GUARDIAN_SUPPORT_SPEC.md §B.5 and hazard #18 flag
// message wording (especially anything implying urgency/emergency) as
// [REVIEW] - "wording that implies emergency may cause a guardian to call
// 999 on the user's behalf, a consequence the user did not choose." Both
// templates below are worded to avoid emergency framing; final wording
// still needs the clinical/safeguarding sign-off the spec calls for before
// this should be treated as finished, not just built.
//
// Both templates identify the sender by name and disclose the Blaze Break
// origin - §B.5's own hard requirement ("the message must always contain
// (a) the user's first name, ... (c) the disclosure that it was sent from
// Blaze Break. These cannot be edited away") - a guardian receiving an
// unexpected text from an unfamiliar number needs both to tell it's real.
export type GuardianSupportTemplateId = 'standard' | 'more_urgent';

export const GUARDIAN_SUPPORT_TEMPLATES: Record<GuardianSupportTemplateId, string> = {
  standard: "Hi {{guardianFirstName}}, it's {{senderFirstName}}. I'm having a difficult moment and I'd really appreciate some support. Could you call or message me when you can? (Sent from the Blaze Break app.)",
  more_urgent: "Hi {{guardianFirstName}}, it's {{senderFirstName}}. I'm feeling overwhelmed and would really appreciate hearing from you as soon as you can. If you cannot reach me, please try again later or contact someone who can support me. (Sent from the Blaze Break app.)",
};

export const isValidGuardianSupportTemplateId = (id: unknown): id is GuardianSupportTemplateId =>
  typeof id === 'string' && id in GUARDIAN_SUPPORT_TEMPLATES;

export interface GuardianSupportMessageNames {
  guardianFirstName: string;
  senderFirstName: string;
}

// No location, no chat content, no inferred state, no diagnosis -
// matching guardian-alert.ts's buildGuardianCallRequestMessage exactly in
// spirit (real names, real disclosure, no fabricated urgency).
export const buildGuardianSupportMessage = (templateId: GuardianSupportTemplateId, names: GuardianSupportMessageNames): string => {
  const guardianName = (names.guardianFirstName || '').trim() || 'there';
  const senderName = (names.senderFirstName || '').trim() || 'A Blaze Break user';
  return GUARDIAN_SUPPORT_TEMPLATES[templateId]
    .replace('{{guardianFirstName}}', guardianName)
    .replace('{{senderFirstName}}', senderName);
};

// Validates a model-proposed "offer the invitation card" tool call. This
// is the ONLY thing the model's own judgement is allowed to influence: a
// boolean UI-rendering decision. It has no bearing on whether anything is
// ever sent, who is contacted, or what a message says - those are always
// separate, later, user-driven steps. `reason` is shown nowhere sensitive;
// it's a short internal string proving the offer was tied to something
// real in the conversation, not fired reflexively - same role
// validateFeatureSuggestion's `reason` field plays for suggest_feature.
export interface GuardianSupportOfferValidationResult {
  valid: boolean;
  error?: string;
}

export const validateGuardianSupportOffer = (args: { reason?: unknown }): GuardianSupportOfferValidationResult => {
  if (typeof args.reason !== 'string' || args.reason.trim().length === 0) {
    return { valid: false, error: 'Offering guardian support needs a real, specific reason tied to what the user just said or asked - not a generic one.' };
  }
  if (args.reason.length > 200) {
    return { valid: false, error: 'Keep the reason under 200 characters.' };
  }
  return { valid: true };
};

// Privacy-preserving analytics only - see docs/GUARDIAN_SUPPORT_INVITATION.md.
// Deliberately a closed enum, not freeform: no event here can ever carry
// chat content, an inferred emotional state, or anything resembling a risk
// label - the type itself is the entire payload beyond routine metadata.
export const GUARDIAN_SUPPORT_EVENT_TYPES = [
  'invitation_shown',
  'invitation_dismissed',
  'contact_flow_opened',
  'contact_flow_cancelled',
  'message_copied',
  'messaging_handoff_opened',
  'send_requested',
  'send_succeeded',
  'send_failed',
  'call_action_opened',
  'no_guardian_configured',
  'resource_route_opened',
] as const;

export type GuardianSupportEventType = typeof GUARDIAN_SUPPORT_EVENT_TYPES[number];

export const isValidGuardianSupportEventType = (type: unknown): type is GuardianSupportEventType =>
  typeof type === 'string' && (GUARDIAN_SUPPORT_EVENT_TYPES as readonly string[]).includes(type);
